from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

__all__ = ("Logger",)


@runtime_checkable
class Logger(Protocol):
    def debug(self, event: str, **kwargs: Any) -> Any: ...
    def info(self, event: str, **kwargs: Any) -> Any: ...
    def warning(self, event: str, **kwargs: Any) -> Any: ...
    def warn(self, event: str, **kwargs: Any) -> Any: ...
    def error(self, event: str, **kwargs: Any) -> Any: ...
    def fatal(self, event: str, **kwargs: Any) -> Any: ...
    def exception(self, event: str, **kwargs: Any) -> Any: ...
    def critical(self, event: str, **kwargs: Any) -> Any: ...
    def set_level(self, level: int) -> None: ...

    def bind(self, **kwargs: Any) -> Logger: ...
    def unbind(self, *keys: str) -> Logger: ...
    def new(self, **kwargs: Any) -> Logger: ...
